name: TodoList CI/CD

on:
  push:
    branches: "master"
  pull_request:
    branches: "master"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: todolist
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean package -DskipTests
    
    
    - name: Build Docker Image
      run: docker build -t todolist-app .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push to Docker Hub
      run: |
        docker tag todolist-app ${{ secrets.DOCKERHUB_USERNAME }}/todolist-app:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/todolist-app:${{ github.sha }}

    - name: Run Tests
      run: mvn test

    - name: Deployed!!
      if: success()
      run: echo "🚀 TodoList App desplegada exitosamente en $(date)"
